# Generated by Django 3.0.4 on 2020-03-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_period', models.DateTimeField()),
                ('terminal', models.CharField(max_length=100)),
                ('arrival_departure', models.CharField(max_length=9)),
                ('domestic_international', models.CharField(max_length=13)),
                ('passenger_count', models.BigIntegerField()),
            ],
        ),
    ]
